# -*- coding: utf-8 -*-
"""12 april practical uses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108GxzerAFNnobBV-kPEmOlsdn34ATl6v

# series and dataframe
"""

import numpy as np
import pandas as pd

x = ["12","23","34","45","56"]
df1 = pd.Series(data = x,index=["a","b","c","d","e"])
df1

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x,index =["a","b","c","d"])
y

x["name"]

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x,index =["a","b","c","d"])
y

"""# setindex"""

df2= y.set_index("location",inplace = True)
print(df2)

x = ["12","23","34","45","56"]
y = pd.DataFrame()

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x,index =["a","b","c","d"])
print(y)

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y.set_index("name",inplace = True)
print(y)

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x,index =pd.RangeIndex(4,8,1))
print(y)

"""# renaming  and resetting"""

x = ["hello","shello","tello","chello"]
df2 = pd.DataFrame(data = x)
X=df2.rename(index={0:"A",1:"B",2:"C",3:"D"})
X

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x)
Z =y.rename(index={0:"A",1:"B",2:"C",3:"D"})
Z

z = Z.reset_index(inplace = True)
print(z)

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x)
y.iloc[2]

x = pd.array([12,23,34,45])
y = pd.Series(data = x,index= ["a","b","c","d"])
y

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x)
city = ["delhi","goa","uk","berlin"]
y["city"] = city
y

z = y.loc[len(y.index)]=["bob",22,"merry"]
z

"""# delete value(loc,iloc)"""

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data = x)
y.drop(2,axis =0)

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y = pd.DataFrame(data=x)
y.drop(1,axis=0)

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y= pd.Series(x)
y
y.drop("age")

y.loc[2]

y.loc[[3,2,1]]

y.loc[1:3]

y.loc[1::]

y.loc[:,["name","age"]]

y.iloc[3]

y.iloc[::1]

y.iloc[1::]

y.iloc[:2:]

x = {"name":["ram","shyam","tom","jerry"],
     "age":[12,23,34,21],
     "location":["hill","park","avenue","rose"]
    }
y= pd.DataFrame(x)
y

"""# masking"""

mask =y["age"]>22
mask

y[mask]

y[(mask)|(y["name"])]

y[(mask)&(y["name"])]

"""# data analysing"""

data = {
    "Continent": ["North America", "Europe", "Asia", "North America", "Asia", "Europe", "North America", "Asia", "Europe", "Asia"],
    "Country": ["United States", "Germany", "China", "Canada", "Japan", "France", "Mexico", "India", "United Kingdom", "Nepal"],
    "Population": [331002651, 83783942, 1439323776, 37742154, 126476461, 65273511, 128932753, 1380004385, 67886011, 29136808]
}
df = pd.DataFrame(data)
df

df.head()

df.tail()

"""# sort value"""

df.sort_values("Country")

df.set_index(["Continent","Country"])

df.iloc[3:]

"""# pivot,pivot table"""

df1 = df.pivot(index="Continent",columns="Country",values = "Population")
df1

df2=df.pivot_table(index="Continent",columns="Country",values = "Population")
print(df2)

"""# stack,unstack"""

df.stack()

df.unstack()

df.melt()

data = {
    "Continent": ["North America", "Europe", "Asia", "North America", "Asia", "Europe", "North America", "Asia", "Europe", "Asia"],
    "Country": ["United States", "Germany", "China", "Canada", "Japan", "France", "Mexico", "India", "United Kingdom", "Nepal"],
    "Population": [331002651, 83783942, 1439323776, 37742154, 126476461, 65273511, 128932753, 1380004385, 67886011, 29136808]
}
df = pd.DataFrame(data)
df

"""# duplicate and removal"""

print(df.duplicated(subset=["Country"]))

df.drop_duplicates(subset="Country")